DROP TABLE IF EXISTS `t_shop`;

CREATE TABLE `t_shop` (
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
`manager_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '店长ID',
`shopname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '店铺名称',
`shoplogo` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '店铺LOGO',
`shopdescription` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '店铺简介',
`shopaddress` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '店铺地址',
`shoplongitude` DECIMAL(10,6) NOT NULL DEFAULT '0.000000' COMMENT '店铺经度',
`shoplatitude` DECIMAL(10,6) NOT NULL DEFAULT '0.000000' COMMENT '店铺纬度',
`createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
`updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最近更新时间',
  PRIMARY KEY (`id`)
)ENGINE=MYISAM  DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `t_manager`;

CREATE TABLE `t_manager` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `areacode` SMALLINT(6) NOT NULL DEFAULT '86' COMMENT '区号',
  `mobile` VARCHAR(18) NOT NULL DEFAULT '' COMMENT '手机号',
  `name` VARCHAR(10) NOT NULL COMMENT '名字',
  `headpath` VARCHAR(255) DEFAULT '' COMMENT '头像',
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
  PRIMARY KEY (`id`)
)ENGINE=MYISAM  DEFAULT CHARSET=utf8;


ALTER TABLE `t_manager` 
ADD state  SMALLINT(6) DEFAULT '1' COMMENT '1：使用中；2：暂停使用；0：无效' 



DROP TABLE IF EXISTS `t_shop_type`;

CREATE TABLE `t_shop_type` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(255) NOT NULL  COMMENT '名字',
  `state` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1：使用中；2：暂停使用；0：无效',
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
  PRIMARY KEY (`id`)
)ENGINE=MYISAM  DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS  `t_goods`;
CREATE TABLE `t_goods` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `goods_sn` VARCHAR(60) NOT NULL DEFAULT '',
  `name` VARCHAR(255) NOT NULL  COMMENT '名字',
  `is_on_sale` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
  `state` TINYINT(4) NOT NULL DEFAULT '1' COMMENT '1：使用中；2：暂停使用；0：无效',
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最近更新时间',
  PRIMARY KEY (`id`)
)ENGINE=MYISAM  DEFAULT CHARSET=utf8;


